apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-hs
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.clientPort }}
    targetPort: {{ .Values.clientPort }}
