apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  type: {{ .Values.service.type}}
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.clientPortExternal }}
    targetPort: {{ .Values.clientPortExternal }}
#  loadBalancerIP: {{ .Values.externalIp }}
