apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-hs
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.clientPort }}
    name: client
  - port: {{ .Values.serverPort }}
    name: server
  - port: {{ .Values.leaderPort }}
    name: leader-election
  clusterIP: None
  selector:
    app: {{ .Values.name }}