apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }} 
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: {{ .Values.name }}-hs
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.clientPort }}
          name: client
        - containerPort: {{ .Values.serverPort }}
          name: server
        - containerPort: {{ .Values.leaderPort }}
          name: leader-election
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
        - name: zookeeper-cfg
          mountPath: /conf/zoo.cfg
          subPath: zoo.cfg
      volumes:
      - name: "zookeeper-cfg"
        configMap:
            name: "zookeeper-cfg"       
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
